version: '3'

services:
  server:
    container_name: Django
    build: ./api
    command: bash -c "
      cd api &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api
    ports:
      - '8000:8000'
