# Generated by Django 3.0.4 on 2020-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.URLField(default='https://img.icons8.com/material/4ac144/256/user-male.png'),
        ),
    ]
